// these options can be edited
// available hardware types can be found here:
// https://github.com/jooby-dev/jooby-docs/blob/main/docs/analog/basics.md#hardware-types
var config = {
    // required field
    hardwareType: 0
};


/*
  Get message from bytes.

  Input is an object with the following fields:
    * bytes - byte array containing the uplink payload, e.g. [255, 230, 255, 0]
    * fPort - uplink fPort

  Output must be an object with the following fields:
    * data - object representing the decoded payload
*/
function decodeUplink( input ) {
    var message = fromBytes(input.bytes, config);

    return {
        data: {
            bytes: input.bytes,
            message
        },
        warnings: [], // optional
        errors: [] // optional (if set, the decoding failed)
    };
}


//#region [autogenerated jooby-codec bundle]
/*{{bundle}}*/
//#endregion
