/*
  Get message from bytes.

  Input is an object with the following fields:
    * bytes - byte array containing the uplink payload, e.g. [255, 230, 255, 0]
    * fPort - uplink fPort

  Output must be an object with the following fields:
    * data - object representing the decoded payload
*/
function decodeUplink( input ) {
    var segment = getDataSegment(input.bytes);
    var message = null;

    // just a single data segment
    if ( segment ) {
        message = fromBytes(segment);

        // there may be a message.error (e.g. mismatched LRC)
        // in that case message.message will contain everything parsed successfully
        // it should be used with caution
    }

    return {
        data: {
            bytes: input.bytes,
            message
        },
        warnings: [], // optional
        errors: [] // optional (if set, the decoding failed)
    };
}


//#region [autogenerated jooby-codec bundle from index.js]
/*{{bundle}}*/
//#endregion
