// these options can be edited
// available hardware types can be found here:
// https://github.com/jooby-dev/jooby-docs/blob/main/docs/analog/basics.md#hardware-types
var config = {
    // required field
    hardwareType: 0,
};


function encodeDownlink ( input ) {
    // input has the following structure:
    // {
    //   field: "value"
    // }
    return {
        bytes: toBytes(input.data.commands), // FRMPayload (byte array)
        fPort: 1,
        warnings: [], // optional
        errors: [], // optional (if set, the encoding failed)
    };
}

function decodeDownlink ( input ) {
    // input has the following structure:
    // {
    //   bytes: [1, 2, 3], // FRMPayload (byte array)
    //   fPort: 1
    // }
    var message = fromBytes(input.bytes, config);

    return {
        data: {
            bytes: input.bytes,
            message,
        },
        warnings: [], // optional
        errors: [], // optional (if set, the decoding failed)
    };
}


//#region [autogenerated jooby-codec bundle]
/*{{bundle}}*/
//#endregion
