// these options can be edited
// available hardware types can be found here:
// https://github.com/jooby-dev/jooby-docs/blob/main/docs/analog/basics.md#hardware-types
var config = {
    hardwareType: 0
};


//#region [autogenerated jooby-codec bundle]
/*{{bundle}}*/
//#endregion


/*
  Incoming arguments:
    * payload - array of bytes
    * metadata - key/value object
*/

var message = fromBytes(payload, config);

// there may be a message.error (e.g. mismatched LRC)
// in that case message.message will contain everything parsed successfully
// it should be used with caution

var result = {
    deviceName: 'Some Device Name',
    deviceType: 'Water Meter',
    attributes: {
        model: 'Device Model',
        serialNumber: 'SN111',
        manufacturer: 'Device Manufacturer'
    },
    message: message.message || message,
    metadata: metadata
};

return result;
