// these options can be edited
// available hardware types can be found here:
// https://github.com/jooby-dev/jooby-docs/blob/main/docs/analog/basics.md#hardware-types
var config = {
    hardwareType: 0
};


/*
  Get message from bytes.

  Input is an object with the following fields:
    * bytes - byte array containing the uplink payload, e.g. [255, 230, 255, 0]
    * fPort - uplink fPort
    * variables - object containing the configured device variables

  Output must be an object with the following fields:
    * data - object representing the decoded payload
*/
function decodeUplink ( input ) {
    const message = fromBytes(input.bytes, config);

    // there may be a message.error (e.g. mismatched LRC)
    // in that case message.message will contain everything parsed successfully
    // it should be used with caution

    return {data: message.message || message};
};


/*
  Get payload bytes from commands.

  Input is an object with the following fields:
    * data - object representing the payload that must be encoded
    * variables - object containing the configured device variables

  Output must be an object with the following fields:
    * bytes - byte array containing the downlink payload
*/
function encodeDownlink ( input ) {
    return {
        bytes: toBytes(input.data.commands, config)
    };
};


//#region [autogenerated jooby-codec bundle]
/*{{bundle}}*/
//#endregion
