// IMPORTANT!!!
// This example only for default uplink data converter.
// Data converters for other integrations use different input and result.
// Find example of uplink data converter for your integration and edit usage of payload and result
// Integrations list: https://thingsboard.io/docs/user-guide/integrations/


//#region [autogenerated jooby-codec bundle from index.js]
/*{{bundle}}*/
//#endregion


/*
  Incoming arguments:
    * payload - array of bytes
    * metadata - key/value object
*/

var segment = getDataSegment(payload);
var message = null;

// just a single data segment
if ( segment ) {
    message = fromBytes(segment);

    // there may be a message.error (e.g. mismatched LRC)
    // in that case message.message will contain everything parsed successfully
    // it should be used with caution
}

var result = {
    // required property, set to real device name from payload/metadata depending on integration
    // empty value throw an error in converter
    deviceName: '',

    deviceType: 'Water Meter',
    attributes: {
        model: 'Device Model',
        serialNumber: 'SN111',
        manufacturer: 'Device Manufacturer'
    },
    telemetry: {
        // telemetry display only primitive, i.e. string and numbers
        // for example only!
        message: JSON.stringify(message.message || message)
    },
    metadata: metadata
};

return result;
