// this is for testing only!

var logs = '';


//#region [autogenerated jooby-codec bundle]
/*{{bundle}}*/
//#endregion


var result = {
    contentType: 'BINARY',
    data: '',
    logs: logs
};

return result;
